SPOOL master_script_log_v1.0.log

SET TIMING ON
SET TIME ON

SET LINE 1000
SET PAGES 50000
SET ECHO ON
SET FEEDBACK ON
SET SCAN OFF
SET TRIMS ON
SET NUMWIDTH 15



SELECT TO_CHAR(SYSDATE,'MM-DD-YYYY HH:MI:SS') FROM DUAL;
SELECT USER  FROM DUAL;

@@ZBR_RESEQUENCER_DDL.sql;
@@TP_METADATA_CONTROL_INSERT.sql;
@@ZBR_RESEQUENCER_PKG_GET_GRP_REC.sql;
@@ZBR_RESEQUENCER_PKG_GET_MSG_REC.sql;
@@ZBR_RESEQUENCER_PKG_CONTROL_TBL_REC.sql;
@@ZBR_RESEQUENCER_PKG_ATTRIBUTE_REC.sql;
@@ZBR_RESEQUENCER_PKG_TP_METADATA_REC.sql;
@@ZEB_RESEQUENCER_VB_MESSAGE_REC.sql;
@@ZEB_RESEQUENCER_VB_GROUP_REC.sql;
@@ZBR_RESEQUENCER_PKG_MSG_REC.sql;
@@ZBR_RESEQUENCER_PKG_GET_GRP_LIST.sql;
@@ZBR_RESEQUENCER_PKG_GET_MSG_LIST.sql;
@@ZBR_RESEQUENCER_PKG_CONTROL_TBL_LIST.sql;
@@ZBR_RESEQUENCER_PKG_ATTRIBUTE_LIST.sql;
@@ZBR_RESEQUENCER_PKG_TP_METADATA_LIST.sql;
@@ZEB_RESEQUENCER_VB_MESSAGE_LIST.sql;
@@ZEB_RESEQUENCER_VB_GROUP_LIST.sql;
@@ZBR_RESEQUENCER_PKG_MSG_LIST.sql;
@@ZBR_RESEQUENCER_PKG_ID_LIST.sql;
@@ZBR_RESEQUENCER_PKG.sql;
show error;

Spool off;

REM ======================================================================
REM ==== END OF SET
REM ======================================================================
