INSERT INTO zeb_resequencer_tp_metadata(TP_ID,TP_NAME,COUNT,PROCESS_NAME,ACTIVE,TP_TIMEZONE) VALUES
('SBL','EBOND_SBL',10,'ZEBSBL_TP_EbondInReq_Int','Y','GMT');
INSERT INTO zeb_resequencer_tp_metadata(TP_ID,TP_NAME,COUNT,PROCESS_NAME,ACTIVE,TP_TIMEZONE) VALUES
('PDS','EBOND_PDS',10,'ZEBSBL_TP_EbondInReq_Int','Y','UTC');
INSERT INTO zeb_resequencer_tp_metadata(TP_ID,TP_NAME,COUNT,PROCESS_NAME,ACTIVE,TP_TIMEZONE) VALUES
('MOXX','EBOND_MOXX',10,'ZEBSBL_TP_EbondInReq_Int','Y','UTC');
INSERT INTO zeb_resequencer_tp_metadata(TP_ID,TP_NAME,COUNT,PROCESS_NAME,ACTIVE,TP_TIMEZONE) VALUES
('BARCODING','EBOND_BARCODING',10,'ZEBSBL_TP_EbondInReq_Int','Y','UTC');

INSERT INTO zeb_reseq_control_tbl(PROCESS_NAME,PROCESS_STATUS,CREATED_BY,CREATED_DATE)
VALUES
('Reseq Group Consumer','NOT RUNNING',USER,LOCALTIMESTAMP);

COMMIT;