  CREATE TABLE ZEB_RESEQUENCER_GROUP 
   (	ID NUMBER GENERATED ALWAYS AS IDENTITY , 
	COMPONENT_DN VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	OPERATION VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	GROUP_ID VARCHAR2(3000 BYTE) NOT NULL ENABLE ,
	PROCESS_ID VARCHAR2(3000 BYTE), 
	STATUS VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	CREATED_DATE VARCHAR2(4000 BYTE), 
	LAST_UPDATED_TIME VARCHAR2(4000 BYTE), 
	ERROR VARCHAR2(4000 BYTE),
	FLOW_ID VARCHAR2(4000 BYTE),	
	TP_NAME VARCHAR2(4000 BYTE),
	CREATED_BY VARCHAR2(4000 BYTE), 
	LAST_UPDATED_BY VARCHAR2(4000 BYTE), 
	START_SEQUENCE_ID VARCHAR2(4000 BYTE), 
	LAST_SEQUENCE_ID VARCHAR2(4000 BYTE), 
	NEXT_SEQUENCE_ID VARCHAR2(4000 BYTE), 
	LAST_RECEIVED_TIME VARCHAR2(4000 BYTE), 
	RESEQUENCER_TYPE VARCHAR2(4000 BYTE) DEFAULT 'FIFO', 
	CONTAINER_ID VARCHAR2(4000 BYTE), 
	TIMEOUT_DURATION VARCHAR2(4000 BYTE), 
	ATTRIBUTE1 VARCHAR2(4000 BYTE), 
	ATTRIBUTE2 VARCHAR2(4000 BYTE), 
	ATTRIBUTE3 VARCHAR2(4000 BYTE), 
	ATTRIBUTE4 VARCHAR2(4000 BYTE), 
	ATTRIBUTE5 VARCHAR2(4000 BYTE), 
	ATTRIBUTE6 VARCHAR2(4000 BYTE), 
	ATTRIBUTE7 VARCHAR2(4000 BYTE), 
	ATTRIBUTE8 VARCHAR2(4000 BYTE), 
	ATTRIBUTE9 VARCHAR2(4000 BYTE), 
	ATTRIBUTE10 VARCHAR2(4000 BYTE), 
	 CONSTRAINT ZRG_GRPRID_PK PRIMARY KEY (GROUP_ID, PROCESS_ID)  ENABLE, 
	 CONSTRAINT ZRG_ID_UK UNIQUE (ID) ENABLE
   ) ;

  CREATE INDEX ZEB_IDX_RESEQ_GRP_CREATED_DT ON ZEB_RESEQUENCER_GROUP (CREATED_DATE) ;
  CREATE BITMAP INDEX ZEB_IDX_RESEQ_GRP_STATUS ON ZEB_RESEQUENCER_GROUP (STATUS) ;
  CREATE INDEX ZEB_IDX_RESEQ_GRP_LAST_UPD_DT ON ZEB_RESEQUENCER_GROUP (LAST_UPDATED_TIME) ;
  
  
  CREATE TABLE ZEB_RESEQUENCER_MESSAGE 
   (ID NUMBER GENERATED ALWAYS AS IDENTITY , 
	OWNER_ID NUMBER, 
	COMPONENT_DN VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	GROUP_ID VARCHAR2(4000 BYTE) NOT NULL ENABLE,  
	SOURCE_URI VARCHAR2(4000 BYTE), 
	PROCESS_ID VARCHAR2(4000 BYTE), 
	STATUS VARCHAR2(4000 BYTE), 
	CREATED_DATE VARCHAR2(4000 BYTE),
	LAST_UPDATED_TIME VARCHAR2(4000 BYTE),
	ERROR VARCHAR2(4000 BYTE),  
	OPERATION VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	LEVEL_DETAIL2 VARCHAR2(4000 BYTE), 
	NAME VARCHAR2(4000 BYTE), 
	TYPE VARCHAR2(4000 BYTE), 
	BIN CLOB, 
	SEQUENCE_ID VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	STANDARD_SEQUENCE_ID VARCHAR2(4000 BYTE), 
	INSTANCE_CREATED VARCHAR2(4000 BYTE), 
	TENANT_ID VARCHAR2(4000 BYTE), 
	FLOW_ID VARCHAR2(4000 BYTE), 
	CONTAINER_ID VARCHAR2(4000 BYTE), 
	CREATED_BY VARCHAR2(4000 BYTE), 
	LAST_UPDATED_BY VARCHAR2(4000 BYTE), 
	START_SEQUENCE_ID VARCHAR2(4000 BYTE), 
	LAST_SEQUENCE_ID VARCHAR2(4000 BYTE), 
	NEXT_SEQUENCE_ID VARCHAR2(4000 BYTE), 
	TP_NAME VARCHAR2(4000 BYTE), 
	PICKED_DATE_TIME VARCHAR2(4000 BYTE), 
	ATTRIBUTE1 VARCHAR2(4000 BYTE), 
	ATTRIBUTE2 VARCHAR2(4000 BYTE), 
	ATTRIBUTE3 VARCHAR2(4000 BYTE), 
	ATTRIBUTE4 VARCHAR2(4000 BYTE), 
	ATTRIBUTE5 VARCHAR2(4000 BYTE), 
	ATTRIBUTE6 VARCHAR2(4000 BYTE), 
	ATTRIBUTE7 VARCHAR2(4000 BYTE), 
	ATTRIBUTE8 VARCHAR2(4000 BYTE), 
	ATTRIBUTE9 VARCHAR2(4000 BYTE), 
	ATTRIBUTE10 VARCHAR2(4000 BYTE), 
	 CONSTRAINT ZRM_SEQID_PK PRIMARY KEY (SEQUENCE_ID)  ENABLE, 
	 CONSTRAINT ZRG_ID_FK FOREIGN KEY (OWNER_ID)
	  REFERENCES ZEB_RESEQUENCER_GROUP (ID) ENABLE
   )  ;

  CREATE INDEX ZEB_IDX_RESEQ_MSG_CREATED_DT ON ZEB_RESEQUENCER_MESSAGE (CREATED_DATE);
  CREATE INDEX ZEB_IDX_RESEQ_MSG_COMP_DN ON ZEB_RESEQUENCER_MESSAGE (COMPONENT_DN);
  CREATE INDEX ZEB_IDX_RESEQ_MSG_STATUS ON ZEB_RESEQUENCER_MESSAGE (STATUS);
  CREATE INDEX ZEB_IDX_RESEQ_MSG_GRP_ID ON ZEB_RESEQUENCER_MESSAGE (GROUP_ID);
  CREATE INDEX ZEB_IDX_RESEQ_MSG_LAST_UPD_DT ON ZEB_RESEQUENCER_MESSAGE (LAST_UPDATED_TIME);
  
  CREATE TABLE ZEB_RESEQUENCER_TP_METADATA 
   (ID NUMBER GENERATED ALWAYS AS IDENTITY , 
	TP_ID VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	TP_NAME VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	COUNT NUMBER, 
	PROCESS_NAME VARCHAR2(4000 BYTE), 
	ACTIVE VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	TP_TIMEZONE VARCHAR2(4000 BYTE), 
	ATTRIBUTE1 VARCHAR2(4000 BYTE), 
	ATTRIBUTE2 VARCHAR2(4000 BYTE), 
	ATTRIBUTE3 VARCHAR2(4000 BYTE), 
	ATTRIBUTE4 VARCHAR2(4000 BYTE), 
	ATTRIBUTE5 VARCHAR2(4000 BYTE), 
	ATTRIBUTE6 VARCHAR2(4000 BYTE),
	ATTRIBUTE7 VARCHAR2(4000 BYTE),
	ATTRIBUTE8 VARCHAR2(4000 BYTE),
	ATTRIBUTE9 VARCHAR2(4000 BYTE),
	ATTRIBUTE10 VARCHAR2(4000 BYTE),	
	 CONSTRAINT ZRTM_ID_PK PRIMARY KEY (ID) ENABLE
   )  ;
 
  CREATE TABLE ZEB_RESEQ_CONTROL_TBL 
   (PROCESS_ID NUMBER GENERATED ALWAYS AS IDENTITY , 
	PROCESS_NAME VARCHAR2(4000 BYTE), 
	PROCESS_STATUS VARCHAR2(4000 BYTE), 
	CREATED_BY VARCHAR2(4000 BYTE), 
	CREATED_DATE VARCHAR2(4000 BYTE), 
	LAST_UPDATED_DATE VARCHAR2(4000 BYTE)
   ) ;
   
/