CREATE OR REPLACE TYPE ZBR_RESEQUENCER_PKG_CONTROL_TBL_REC IS OBJECT(
PROCESS_ID	NUMBER,
PROCESS_NAME	VARCHAR2(4000 BYTE),
PROCESS_STATUS	VARCHAR2(4000 BYTE),
CREATED_BY	VARCHAR2(4000 BYTE),
CREATED_DATE	VARCHAR2(4000 BYTE),
LAST_UPDATED_DATE	VARCHAR2(4000 BYTE)
);
/